Repository getindata/terraform-null-atlantis-repo-config, pull requests merged in 2023-03, with the labels that each got.

#10 feat!: Refactor workflows and add flags to generate steps
  README.md
  config/workflows.yaml
  examples/complete/main.tf
  main.tf
  variables.tf
  workflow_templates.tf
Labels: release/major

#11 feat: New configuration with infracost
  README.md
  examples/complete/main.tf
  main.tf
  variables.tf
Labels: release/minor

#12 fix: Post infracost comment only once
  main.tf
Labels: release/patch
